// Generated by scripts/build-item-table.mjs — do not edit by hand.
import type { HeldItem } from './item.model';

export const ITEM_TABLE: HeldItem[] = [
  {
    id: 'silkscarf',
    name: 'Seidenschal',
    category: 'booster',
    spritenum: 444,
    desc: 'Verstärkt Normal-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Normal',
      mult: 1.2
    }
  },
  {
    id: 'charcoal',
    name: 'Holzkohle',
    category: 'booster',
    spritenum: 61,
    desc: 'Verstärkt Feuer-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Fire',
      mult: 1.2
    }
  },
  {
    id: 'mysticwater',
    name: 'Zauberwasser',
    category: 'booster',
    spritenum: 300,
    desc: 'Verstärkt Wasser-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Water',
      mult: 1.2
    }
  },
  {
    id: 'magnet',
    name: 'Magnet',
    category: 'booster',
    spritenum: 273,
    desc: 'Verstärkt Elektro-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Electric',
      mult: 1.2
    }
  },
  {
    id: 'miracleseed',
    name: 'Wundersaat',
    category: 'booster',
    spritenum: 292,
    desc: 'Verstärkt Pflanzen-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Grass',
      mult: 1.2
    }
  },
  {
    id: 'nevermeltice',
    name: 'Ewiges Eis',
    category: 'booster',
    spritenum: 305,
    desc: 'Verstärkt Eis-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Ice',
      mult: 1.2
    }
  },
  {
    id: 'blackbelt',
    name: 'Schwarzgurt',
    category: 'booster',
    spritenum: 32,
    desc: 'Verstärkt Kampf-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Fighting',
      mult: 1.2
    }
  },
  {
    id: 'poisonbarb',
    name: 'Giftstich',
    category: 'booster',
    spritenum: 343,
    desc: 'Verstärkt Gift-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Poison',
      mult: 1.2
    }
  },
  {
    id: 'softsand',
    name: 'Pudersand',
    category: 'booster',
    spritenum: 456,
    desc: 'Verstärkt Boden-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Ground',
      mult: 1.2
    }
  },
  {
    id: 'sharpbeak',
    name: 'Spitzer Schnabel',
    category: 'booster',
    spritenum: 436,
    desc: 'Verstärkt Flug-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Flying',
      mult: 1.2
    }
  },
  {
    id: 'twistedspoon',
    name: 'Krummlöffel',
    category: 'booster',
    spritenum: 520,
    desc: 'Verstärkt Psycho-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Psychic',
      mult: 1.2
    }
  },
  {
    id: 'silverpowder',
    name: 'Silberstaub',
    category: 'booster',
    spritenum: 447,
    desc: 'Verstärkt Käfer-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Bug',
      mult: 1.2
    }
  },
  {
    id: 'hardstone',
    name: 'Granitstein',
    category: 'booster',
    spritenum: 187,
    desc: 'Verstärkt Gesteins-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Rock',
      mult: 1.2
    }
  },
  {
    id: 'spelltag',
    name: 'Bannsticker',
    category: 'booster',
    spritenum: 461,
    desc: 'Verstärkt Geister-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Ghost',
      mult: 1.2
    }
  },
  {
    id: 'dragonfang',
    name: 'Drachenzahn',
    category: 'booster',
    spritenum: 106,
    desc: 'Verstärkt Drachen-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Dragon',
      mult: 1.2
    }
  },
  {
    id: 'blackglasses',
    name: 'Schattenbrille',
    category: 'booster',
    spritenum: 35,
    desc: 'Verstärkt Unlicht-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Dark',
      mult: 1.2
    }
  },
  {
    id: 'metalcoat',
    name: 'Metallmantel',
    category: 'booster',
    spritenum: 286,
    desc: 'Verstärkt Stahl-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Steel',
      mult: 1.2
    }
  },
  {
    id: 'pixieplate',
    name: 'Feentafel',
    category: 'booster',
    spritenum: 610,
    desc: 'Verstärkt Feen-Attacken um 20 %.',
    effect: {
      kind: 'typeBoost',
      type: 'Fairy',
      mult: 1.2
    }
  },
  {
    id: 'normalgem',
    name: 'Normaljuwel',
    category: 'gem',
    spritenum: 307,
    desc: 'Verstärkt die erste Normal-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Normal'
    }
  },
  {
    id: 'firegem',
    name: 'Feuerjuwel',
    category: 'gem',
    spritenum: 141,
    desc: 'Verstärkt die erste Feuer-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Fire'
    }
  },
  {
    id: 'watergem',
    name: 'Wasserjuwel',
    category: 'gem',
    spritenum: 528,
    desc: 'Verstärkt die erste Wasser-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Water'
    }
  },
  {
    id: 'electricgem',
    name: 'Elektrojuwel',
    category: 'gem',
    spritenum: 120,
    desc: 'Verstärkt die erste Elektro-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Electric'
    }
  },
  {
    id: 'grassgem',
    name: 'Pflanzenjuwel',
    category: 'gem',
    spritenum: 172,
    desc: 'Verstärkt die erste Pflanzen-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Grass'
    }
  },
  {
    id: 'icegem',
    name: 'Eisjuwel',
    category: 'gem',
    spritenum: 218,
    desc: 'Verstärkt die erste Eis-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Ice'
    }
  },
  {
    id: 'fightinggem',
    name: 'Kampfjuwel',
    category: 'gem',
    spritenum: 139,
    desc: 'Verstärkt die erste Kampf-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Fighting'
    }
  },
  {
    id: 'poisongem',
    name: 'Giftjuwel',
    category: 'gem',
    spritenum: 344,
    desc: 'Verstärkt die erste Gift-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Poison'
    }
  },
  {
    id: 'groundgem',
    name: 'Bodenjuwel',
    category: 'gem',
    spritenum: 182,
    desc: 'Verstärkt die erste Boden-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Ground'
    }
  },
  {
    id: 'flyinggem',
    name: 'Flugjuwel',
    category: 'gem',
    spritenum: 149,
    desc: 'Verstärkt die erste Flug-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Flying'
    }
  },
  {
    id: 'psychicgem',
    name: 'Psychojuwel',
    category: 'gem',
    spritenum: 369,
    desc: 'Verstärkt die erste Psycho-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Psychic'
    }
  },
  {
    id: 'buggem',
    name: 'Käferjuwel',
    category: 'gem',
    spritenum: 53,
    desc: 'Verstärkt die erste Käfer-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Bug'
    }
  },
  {
    id: 'rockgem',
    name: 'Gesteinsjuwel',
    category: 'gem',
    spritenum: 415,
    desc: 'Verstärkt die erste Gesteins-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Rock'
    }
  },
  {
    id: 'ghostgem',
    name: 'Geisterjuwel',
    category: 'gem',
    spritenum: 161,
    desc: 'Verstärkt die erste Geister-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Ghost'
    }
  },
  {
    id: 'dragongem',
    name: 'Drakojuwel',
    category: 'gem',
    spritenum: 107,
    desc: 'Verstärkt die erste Drachen-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Dragon'
    }
  },
  {
    id: 'darkgem',
    name: 'Unlichtjuwel',
    category: 'gem',
    spritenum: 89,
    desc: 'Verstärkt die erste Unlicht-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Dark'
    }
  },
  {
    id: 'steelgem',
    name: 'Stahljuwel',
    category: 'gem',
    spritenum: 473,
    desc: 'Verstärkt die erste Stahl-Attacke um 30 %. Einmalig.',
    effect: {
      kind: 'gem',
      type: 'Steel'
    }
  },
  {
    id: 'occaberry',
    name: 'Koakobeere',
    category: 'berry',
    spritenum: 311,
    desc: 'Halbiert einen sehr effektiven Feuer-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Fire'
    }
  },
  {
    id: 'passhoberry',
    name: 'Foepasbeere',
    category: 'berry',
    spritenum: 329,
    desc: 'Halbiert einen sehr effektiven Wasser-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Water'
    }
  },
  {
    id: 'wacanberry',
    name: 'Kerzalbeere',
    category: 'berry',
    spritenum: 526,
    desc: 'Halbiert einen sehr effektiven Elektro-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Electric'
    }
  },
  {
    id: 'rindoberry',
    name: 'Grindobeere',
    category: 'berry',
    spritenum: 409,
    desc: 'Halbiert einen sehr effektiven Pflanzen-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Grass'
    }
  },
  {
    id: 'yacheberry',
    name: 'Kiroyabeere',
    category: 'berry',
    spritenum: 567,
    desc: 'Halbiert einen sehr effektiven Eis-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Ice'
    }
  },
  {
    id: 'chopleberry',
    name: 'Rospelbeere',
    category: 'berry',
    spritenum: 71,
    desc: 'Halbiert einen sehr effektiven Kampf-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Fighting'
    }
  },
  {
    id: 'kebiaberry',
    name: 'Grarzbeere',
    category: 'berry',
    spritenum: 234,
    desc: 'Halbiert einen sehr effektiven Gift-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Poison'
    }
  },
  {
    id: 'shucaberry',
    name: 'Schukebeere',
    category: 'berry',
    spritenum: 443,
    desc: 'Halbiert einen sehr effektiven Boden-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Ground'
    }
  },
  {
    id: 'cobaberry',
    name: 'Kobabeere',
    category: 'berry',
    spritenum: 76,
    desc: 'Halbiert einen sehr effektiven Flug-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Flying'
    }
  },
  {
    id: 'payapaberry',
    name: 'Pyapabeere',
    category: 'berry',
    spritenum: 330,
    desc: 'Halbiert einen sehr effektiven Psycho-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Psychic'
    }
  },
  {
    id: 'tangaberry',
    name: 'Tanigabeere',
    category: 'berry',
    spritenum: 487,
    desc: 'Halbiert einen sehr effektiven Käfer-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Bug'
    }
  },
  {
    id: 'chartiberry',
    name: 'Chiaribeere',
    category: 'berry',
    spritenum: 62,
    desc: 'Halbiert einen sehr effektiven Gesteins-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Rock'
    }
  },
  {
    id: 'kasibberry',
    name: 'Zitarzbeere',
    category: 'berry',
    spritenum: 233,
    desc: 'Halbiert einen sehr effektiven Geister-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Ghost'
    }
  },
  {
    id: 'habanberry',
    name: 'Terirobeere',
    category: 'berry',
    spritenum: 185,
    desc: 'Halbiert einen sehr effektiven Drachen-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Dragon'
    }
  },
  {
    id: 'colburberry',
    name: 'Burleobeere',
    category: 'berry',
    spritenum: 78,
    desc: 'Halbiert einen sehr effektiven Unlicht-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Dark'
    }
  },
  {
    id: 'babiriberry',
    name: 'Babiribeere',
    category: 'berry',
    spritenum: 17,
    desc: 'Halbiert einen sehr effektiven Stahl-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Steel'
    }
  },
  {
    id: 'chilanberry',
    name: 'Latchibeere',
    category: 'berry',
    spritenum: 66,
    desc: 'Halbiert den Schaden einer Normal-Attacke. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Normal'
    }
  },
  {
    id: 'roseliberry',
    name: 'Hibisbeere',
    category: 'berry',
    spritenum: 603,
    desc: 'Halbiert einen sehr effektiven Feen-Treffer. Einmalig.',
    effect: {
      kind: 'resistBerry',
      type: 'Fairy'
    }
  },
  {
    id: 'sitrusberry',
    name: 'Tsitrubeere',
    category: 'berry',
    spritenum: 448,
    desc: 'Füllt bei halben KP ¼ der KP auf. Einmalig.',
    effect: {
      kind: 'healBerry',
      threshold: 0.5,
      fraction: 0.25
    }
  },
  {
    id: 'oranberry',
    name: 'Sinelbeere',
    category: 'berry',
    spritenum: 319,
    desc: 'Füllt bei halben KP 10 KP auf. Einmalig.',
    effect: {
      kind: 'healBerry',
      threshold: 0.5,
      flat: 10
    }
  },
  {
    id: 'cheriberry',
    name: 'Amrenabeere',
    category: 'berry',
    spritenum: 63,
    desc: 'Heilt Paralyse. Einmalig.',
    effect: {
      kind: 'cureBerry',
      cures: ['par']
    }
  },
  {
    id: 'chestoberry',
    name: 'Maronbeere',
    category: 'berry',
    spritenum: 65,
    desc: 'Heilt Schlaf. Einmalig.',
    effect: {
      kind: 'cureBerry',
      cures: ['slp']
    }
  },
  {
    id: 'pechaberry',
    name: 'Pirsifbeere',
    category: 'berry',
    spritenum: 333,
    desc: 'Heilt Vergiftung. Einmalig.',
    effect: {
      kind: 'cureBerry',
      cures: ['psn', 'tox']
    }
  },
  {
    id: 'rawstberry',
    name: 'Fragiabeere',
    category: 'berry',
    spritenum: 381,
    desc: 'Heilt Verbrennung. Einmalig.',
    effect: {
      kind: 'cureBerry',
      cures: ['brn']
    }
  },
  {
    id: 'aspearberry',
    name: 'Wilbirbeere',
    category: 'berry',
    spritenum: 13,
    desc: 'Heilt Einfrieren. Einmalig.',
    effect: {
      kind: 'cureBerry',
      cures: ['frz']
    }
  },
  {
    id: 'persimberry',
    name: 'Persimbeere',
    category: 'berry',
    spritenum: 334,
    desc: 'Heilt Verwirrung. Einmalig.',
    effect: {
      kind: 'cureBerry',
      cures: ['confusion']
    }
  },
  {
    id: 'lumberry',
    name: 'Prunusbeere',
    category: 'berry',
    spritenum: 262,
    desc: 'Heilt jedes Statusproblem und Verwirrung. Einmalig.',
    effect: {
      kind: 'cureBerry',
      cures: ['par', 'slp', 'psn', 'tox', 'brn', 'frz', 'confusion']
    }
  },
  {
    id: 'salacberry',
    name: 'Salkabeere',
    category: 'berry',
    spritenum: 426,
    desc: 'Erhöht bei ¼ KP Initiative. Einmalig.',
    effect: {
      kind: 'pinchBerry',
      stat: 'spe',
      stages: 1
    }
  },
  {
    id: 'liechiberry',
    name: 'Lydzibeere',
    category: 'berry',
    spritenum: 248,
    desc: 'Erhöht bei ¼ KP Angriff. Einmalig.',
    effect: {
      kind: 'pinchBerry',
      stat: 'atk',
      stages: 1
    }
  },
  {
    id: 'petayaberry',
    name: 'Tahaybeere',
    category: 'berry',
    spritenum: 335,
    desc: 'Erhöht bei ¼ KP Spezial-Angriff. Einmalig.',
    effect: {
      kind: 'pinchBerry',
      stat: 'spa',
      stages: 1
    }
  },
  {
    id: 'ganlonberry',
    name: 'Linganbeere',
    category: 'berry',
    spritenum: 158,
    desc: 'Erhöht bei ¼ KP Verteidigung. Einmalig.',
    effect: {
      kind: 'pinchBerry',
      stat: 'def',
      stages: 1
    }
  },
  {
    id: 'apicotberry',
    name: 'Apikobeere',
    category: 'berry',
    spritenum: 10,
    desc: 'Erhöht bei ¼ KP Spezial-Verteidigung. Einmalig.',
    effect: {
      kind: 'pinchBerry',
      stat: 'spd',
      stages: 1
    }
  },
  {
    id: 'starfberry',
    name: 'Krambobeere',
    category: 'berry',
    spritenum: 472,
    desc: 'Erhöht bei ¼ KP einen zufälligen Wert stark. Einmalig.',
    effect: {
      kind: 'pinchBerry',
      stat: 'random',
      stages: 2
    }
  },
  {
    id: 'jabocaberry',
    name: 'Jabocabeere',
    category: 'berry',
    spritenum: 230,
    desc: 'Physischer Angreifer verliert ⅛ seiner KP. Einmalig.',
    effect: {
      kind: 'retaliateBerry',
      category: 'Physical'
    }
  },
  {
    id: 'rowapberry',
    name: 'Roselbeere',
    category: 'berry',
    spritenum: 420,
    desc: 'Spezieller Angreifer verliert ⅛ seiner KP. Einmalig.',
    effect: {
      kind: 'retaliateBerry',
      category: 'Special'
    }
  },
  {
    id: 'leftovers',
    name: 'Überreste',
    category: 'battle',
    spritenum: 242,
    desc: 'Füllt am Rundenende 1/16 der KP auf.',
    effect: {
      kind: 'battle',
      id: 'leftovers'
    }
  },
  {
    id: 'blacksludge',
    name: 'Giftschleim',
    category: 'battle',
    spritenum: 34,
    desc: 'Gift-Pokémon: +1/16 KP pro Runde, andere verlieren ⅛.',
    effect: {
      kind: 'battle',
      id: 'blacksludge'
    }
  },
  {
    id: 'lifeorb',
    name: 'Leben-Orb',
    category: 'battle',
    spritenum: 249,
    desc: 'Attacken +30 %, kostet pro Treffer 1/10 der KP.',
    effect: {
      kind: 'battle',
      id: 'lifeorb'
    }
  },
  {
    id: 'choiceband',
    name: 'Wahlband',
    category: 'battle',
    spritenum: 68,
    desc: 'Angriff ×1,5, aber nur eine Attacke wählbar.',
    effect: {
      kind: 'battle',
      id: 'choiceband'
    }
  },
  {
    id: 'choicespecs',
    name: 'Wahlbrille',
    category: 'battle',
    spritenum: 70,
    desc: 'Spezial-Angriff ×1,5, aber nur eine Attacke wählbar.',
    effect: {
      kind: 'battle',
      id: 'choicespecs'
    }
  },
  {
    id: 'choicescarf',
    name: 'Wahlschal',
    category: 'battle',
    spritenum: 69,
    desc: 'Initiative ×1,5, aber nur eine Attacke wählbar.',
    effect: {
      kind: 'battle',
      id: 'choicescarf'
    }
  },
  {
    id: 'focussash',
    name: 'Fokusgurt',
    category: 'battle',
    spritenum: 151,
    desc: 'Übersteht bei vollen KP einen K.-o.-Treffer mit 1 KP. Einmalig.',
    effect: {
      kind: 'battle',
      id: 'focussash'
    }
  },
  {
    id: 'expertbelt',
    name: 'Expertengurt',
    category: 'battle',
    spritenum: 132,
    desc: 'Sehr effektive Attacken +20 %.',
    effect: {
      kind: 'battle',
      id: 'expertbelt'
    }
  },
  {
    id: 'muscleband',
    name: 'Muskelband',
    category: 'battle',
    spritenum: 297,
    desc: 'Physische Attacken +10 %.',
    effect: {
      kind: 'battle',
      id: 'muscleband'
    }
  },
  {
    id: 'wiseglasses',
    name: 'Schlaubrille',
    category: 'battle',
    spritenum: 539,
    desc: 'Spezielle Attacken +10 %.',
    effect: {
      kind: 'battle',
      id: 'wiseglasses'
    }
  },
  {
    id: 'eviolite',
    name: 'Evolith',
    category: 'battle',
    spritenum: 130,
    desc: 'Verteidigung und Sp.-Vert. ×1,5, solange es sich entwickeln kann.',
    effect: {
      kind: 'battle',
      id: 'eviolite'
    }
  },
  {
    id: 'assaultvest',
    name: 'Offensivweste',
    category: 'battle',
    spritenum: 581,
    desc: 'Spezial-Verteidigung ×1,5, aber keine Status-Attacken.',
    effect: {
      kind: 'battle',
      id: 'assaultvest'
    }
  },
  {
    id: 'rockyhelmet',
    name: 'Beulenhelm',
    category: 'battle',
    spritenum: 417,
    desc: 'Angreifer mit Kontakt verliert ⅙ seiner KP.',
    effect: {
      kind: 'battle',
      id: 'rockyhelmet'
    }
  },
  {
    id: 'airballoon',
    name: 'Luftballon',
    category: 'battle',
    spritenum: 6,
    desc: 'Immun gegen Boden-Attacken, bis es getroffen wird.',
    effect: {
      kind: 'battle',
      id: 'airballoon'
    }
  },
  {
    id: 'brightpowder',
    name: 'Blendpuder',
    category: 'battle',
    spritenum: 51,
    desc: 'Gegnerische Attacken treffen seltener (×0,9).',
    effect: {
      kind: 'battle',
      id: 'brightpowder'
    }
  },
  {
    id: 'widelens',
    name: 'Großlinse',
    category: 'battle',
    spritenum: 537,
    desc: 'Eigene Attacken treffen öfter (×1,1).',
    effect: {
      kind: 'battle',
      id: 'widelens'
    }
  },
  {
    id: 'powerherb',
    name: 'Energiekraut',
    category: 'battle',
    spritenum: 358,
    desc: 'Zwei-Runden-Attacke sofort einsetzen. Einmalig.',
    effect: {
      kind: 'battle',
      id: 'powerherb'
    }
  },
  {
    id: 'whiteherb',
    name: 'Schlohkraut',
    category: 'battle',
    spritenum: 535,
    desc: 'Setzt gesenkte Statuswerte zurück. Einmalig.',
    effect: {
      kind: 'battle',
      id: 'whiteherb'
    }
  },
  {
    id: 'shellbell',
    name: 'Muschelglocke',
    category: 'battle',
    spritenum: 438,
    desc: 'Füllt ⅛ des zugefügten Schadens als KP auf.',
    effect: {
      kind: 'battle',
      id: 'shellbell'
    }
  }
];
